name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Get Depencencies
      run: yarn install
    
    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
